### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hgsgtk** [hgsgtk/lamda-slack-go#1]
# Lamda Go slack

## 関心リスト

- [x] ローカル環境の構築: SAMを試す
	- https://github.com/hgsgtk/go-snippets/tree/master/sam-lamda-hello
- [x] Lambdaでのevent handlingのやり方をざっくり
	- CloudWatchEventsの設定で解決
- [x] Hello worldイベントがちゃんと動く
- [x] LamdaからRDSにアクセスする
- [ ] Eventトリガーを受けての起動関数の場合のローカル環境
- [ ] デプロイ方法、SAM？
- [x] Database proxies
- [x] Lamda Go database access
	- 普通にsqlパッケージなりなんなりでやればいい
- [x] Logはどちらへ
	- CloudWatchLogsに流れる
- [x] Lamda to slack -> VPC内に入れる場合は外部インターネットアクセスをする場合、NAT Gatewayを介さないといけない
- [x] slack apiへの通信がタイムアウトする
- [ ] テスタビリティを考慮したコードにする
- [x] Lamdaにおけるエラーハンドリング
	- errorを返す
- [x] Lamdaが終了になる前にアプリケーションでタイムアウト設定してないと何もわからない
- [x] 設定情報、特に秘匿情報をいかに扱うか
- [ ] すべてTerraformに移植する
- [ ] 出力方式は抽象的で差し替え可能になってほしい
- [ ] 設定情報の取得について抽象化されてほしい、というか項目名は自らIssue
- [x] AWS Secrets Managerを使う
- [x] Go moduleでの依存パッケージ管理
- [x] Secrets Managerを使う際の適切なIAMポリシー
- [ ] 設定情報がほしいという関心に対して、手段を抽象化する、SecretsManagerなり

# Refs

## Go関連
- https://github.com/aws/aws-lambda-go/tree/master/events
	- 各種のイベントに合わせて色々サンプルがある
- https://medium.com/@yunskilic/developing-golang-aws-lambda-functions-with-gorm-amazon-rds-for-postgresql-c5efbcbd0b0d
- https://dev.classmethod.jp/cloud/aws/aws-lambda-supports-go/

```
・func ()
・func () error
・func (TIn), error
・func () (TOut, error)
・func (context.Context) error
・func (context.Context, TIn) error
・func (context.Context) (TOut, error)
・func (context.Context, TIn) (TOut, error)
```

## zipファイルのbuildは専用ツールを使う
 -https://blog.narumium.net/2019/03/02/%E3%80%90go%E3%80%91aws-lambda%E3%81%A7go%E3%81%A7%E4%BD%9C%E3%81%A3%E3%81%9F%E3%83%90%E3%82%A4%E3%83%8A%E3%83%AA%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B/
 
 > github.com/aws/aws-lambda-go/cmd/build-lambda-zip

## SAM関連
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html
- https://qiita.com/t-hirai777/items/5d6df88eb69469ed1bdf

## CloudWatch Events
- https://qiita.com/Toshinori_Hayashi/items/5b0a72dc64ced91717c0
- https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/tutorial-scheduled-events-schedule-expressions.html

> Lambda コンソールを使用している場合は、式に cron プレフィックスを含めないでください。

ふむ、そうじゃなかったらいけるんか？

## Layer

- https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/configuration-layers.html

## Database proxy
- https://dev.classmethod.jp/cloud/aws/rds-proxy-reinvent2019/

> 「Lambda - RDSってアンチパターンなんでしょ？」と言われる主要要因の一つの同時接続数の問題が解決できるはず

なるほどね、サーバーレスのRDSコネクションの問題はここにあるのね

## Lamda-RDS
- https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/services-rds-tutorial.html

`AWSLambdaVPCAccessExecutionRole` policyをroleにAttachする

あとは普通にデータベースにアクセスしてねっていう話か

> Error by connection database &errors.errorString{s:"sql: unknown driver \"mysql\" (forgotten import?)"}END RequestId: 53f93ce5-a441-4807-88fc-8d8d1215f001

基本的な話でdriverが入ってないといけない
そして、VPC内にないとだめ

> Error by ping database &mysql.MySQLError{Number:0x419, Message:"Unknown database 'camp'"}END RequestId: 9f7ecc6d-bcb9-4764-a6ac-8e7231eabc64

さらにデータベースにそういうのはないよという怒られが発生したので、やっていく

## Lamda-slack
- https://dev.classmethod.jp/cloud/aws/github-slack/
- まずは具象的に直接やってみる
- https://github.com/nlopes/slack/blob/master/examples/messages/messages.go

> Error by sending slack message: missing_scope (detail: &errors.errorString{s:"missing_scope"})

ネットワークが通ったので、さてこのエラー

### V2のInstall
- https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/install-cliv2-macOS.html

## Lamda外部通信
- VPCを有効にした場合のLambda functionではデフォルトのインターネットアクセスが失われるため、セキュリティグループにて外部通信を許可し、NATゲートウェイを作成する

> VPC を有効にすると、Lambda 関数はデフォルトのインターネットアクセスを失います。関数に外部インターネットアクセスが必要な場合は、セキュリティグループがアウトバウンド接続を許可し、VPC に NAT ゲートウェイがあることを確認します。

- https://aws.amazon.com/jp/premiumsupport/knowledge-center/internet-access-lambda-function/

> 関連する VPC がパブリックサブネットに NAT ゲートウェイ (または NAT インスタンス) を持っている必要があります。

- つまり、インターネットゲートウェイがルートテーブルに存在している必要がある

- https://docs.aws.amazon.com/ja_jp/vpc/latest/userguide/vpc-nat-gateway.html

ルートテーブルに指定するべきNatGatewayはpublic subnetに存在する必要がある。つまり、internet gatewayにリクエストが行くやつ

## slack
- https://qiita.com/RuyPKG/items/5ac07ddc04432ee7641b
- botユーザーにしないといけない

## AWS Secrets Manager

- errorMessage

>   "errorMessage": "AccessDeniedException: User: arn:aws:sts::556389769861:assumed-role/myFunctionHello-role-glse7tsm/myFunctionHello is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:ap-northeast-1:556389769861:secret:database-1-gorilla-FM7fQR\n\tstatus code: 400, request id: 9979b593-82b6-4d6f-a9ce-0a6b7aa0dd5e",

>   "errorMessage": "{\"username\":\"admin\",\"password\":\"adminadmin\",\"engine\":\"mysql\",\"host\":\"database-1.cluster-cw4f1mgwq885.ap-northeast-1.rds.amazonaws.com\",\"port\":3306,\"dbClusterIdentifier\":\"database-1\"}: ",
